/* location */
export const GET_LOCATION = 'GET_LOCATION';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
/* weather */
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_CITY_WEATHER = 'GET_CITY_WEATHER';
export const CURRENT_WEATHER_SUCCESS = 'CURRENT_WEATHER_SUCCESS';
export const CITY_WEATHER_SUCCESS = 'CITY_WEATHER_SUCCESS';
